# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
name: "🔄 CI"
on:
  push:
    branches:
      - develop
      - master
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore

jobs:
  draft_release:
    if: "
      startsWith(github.event.head_commit.message, 'release:') || 
      startsWith(github.event.head_commit.message, 'release(') || 
      startsWith(github.event.head_commit.message, 'rel:') || 
      startsWith(github.event.head_commit.message, 'rel(')
    "
    uses: ./.github/workflows/release.yml
