name: "test: changelogs generation"

on:
  workflow_dispatch:
    inputs:
      from:
        description: 'From version'
        required: true
      to:
        description: 'To version'
        required: true
      next-version:
        description: 'Next version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.3.0

      - name: Generate Changelog
        uses: ./
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from: ${{ github.event.inputs.from }}
          to: ${{ github.event.inputs.to }}
          next-version: ${{ github.event.inputs.next-version }}